name: Go

on: [push]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go_version: ["1.14", "1.15"]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go_version }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go run test.go
    
    # FIXME: re-enable once goroutine limit control works
    # - name: Fuzz (with race)
    #   run: go run test.go -- -race -v -service.fuzz=true -service.fuzztime=5s -service.fuzzservicelim=200 -service.fuzzrunnerlim=10
    
    - name: Fuzz (fixed seed)
      run: go run test.go -- -v -service.fuzz=true -service.fuzzseed=1 -service.fuzztime=5s
      
    - name: Fuzz (randomised)
      run: go run test.go -- -v -service.fuzz=true -service.fuzztime=5s
